### ISSUE TITLE
crash on server

### ISSUE THREAD

**Issue by XBlackLeopardX** [XCompWiz/LookingGlass#1]
I get this crash on my server when looking glass is installed on startup
https://gist.github.com/XBlackLeopardX/d88e591c28d63341ee99

**Comment by XCompWiz** [comment]
Whoops. I think I know what caused this.  I'll get a fix build up in a little bit. :)

**Comment by XBlackLeopardX** [comment]
okay thanks! :)
Btw this mod has so much potential i really hope it gets popular and have the api used
