### ISSUE TITLE
LookingGlass and JorneyMap

### ISSUE THREAD

**Issue by sonikfyre** [XCompWiz/LookingGlass#10]
Custom modpack with Mystcraft 0.12.0 and LookingGlass 0.1.2 with JourneyMap 5.1.0

Activating a linking book to the "overworld" caused the issue with JourneyMap where it broke the borders of the minimap. The clipping of all the caves and stuff as you can see in the screenshot behind the map is also caused at the same time that the map goes haywire.

https://dl.dropboxusercontent.com/u/68340301/Clipping%20Screen%20shot.png

Confirmed that it is an issue with LookingGlass, removal of the jar and config fixed issue entirely.

**Comment by heldplayer** [comment]
See #7

**Comment by XCompWiz** [comment]
Closing as duplicate.
