### ISSUE TITLE
IWorldView cannot be attached to entities and move along with them...

### ISSUE THREAD

**Issue by TheTemportalist** [XCompWiz/LookingGlass#13]
But what if I want to put one in a tardis..... :(

**Comment by Guichaguri** [comment]
Why not?
Since it gives you a texture id, you can render it whenever you like.
(I might be saying something wrong, I don't know if the LookingGlass API changed since I used it)

**Comment by heldplayer** [comment]
I think they are talking about the fact that the location of the world view can't be bound to entities.

It would be kind-of possible if the view is from the same dimension as you're in, but I don't think at all possible right now if it's in a different dimension.

**Comment by XCompWiz** [comment]
Both previous comments are correct, depending on which direction you mean.

The texture can be rendered as you like, no issue.

The render source/camera cannot be attached to entities in other dimensions locally, as the client has no knowledge of those entities.
However, you can build an animator to update the camera position and rotation based on either an entity position (if you have that info client side) or using information you send from the server yourself.

This isn't an issue with LookingGlass. You'll need to determine how you want to handle it.
in the future, entities can be synced to clients via LookingGlass and this might get easier, but even then this will be up to you to do.

**Comment by TheTemportalist** [comment]
Thank you for the input. It wasn't as much an issue as just the best way to get in contact with people who know what they are doing :P
