### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by SvEgiiVEteR** [XCompWiz/LookingGlass#17]
Spam in the log and then crash
Spam
http://hastebin.com/jafewokaxu.avrasm
crash
http://hastebin.com/dabiwoleca.md

**Comment by heldplayer** [comment]
The crash report seems to be related to a mod called "More Planets" (Galacticraft addon?)

**Comment by SvEgiiVEteR** [comment]
All true, but the fact that the block is out of mod does not have near.
he can generate in the world ... I'll check.
but it was spam and immediately after the crash.

the world was new and the block is not generated in the world

**Comment by Guichaguri** [comment]
Try removing that mod and see if everything will work.
The crash from LookingGlass was about [filling a chunk](https://github.com/XCompWiz/LookingGlass/blob/master/src/main/java/com/xcompwiz/lookingglass/network/packet/PacketChunkInfo.java#L120) that had the block.

It seems like the dimension of the LookingGlass View had a lot of that block

**Comment by SvEgiiVEteR** [comment]
I tried to turn it off, and far so good ....
    # On the client this disables other world renders entirely, preventing world requests. On the server this disables sending world info to all clients.
    B:disabled=true

**Comment by XCompWiz** [comment]
The original hastebin links seem to have expired.  Since the only comments here seem to point at it being another mod, I'm going to close this until someone says otherwise.
