### ISSUE TITLE
LookingGlass Causes things to speed up with BetterRecords mod and Security Craft mod

### ISSUE THREAD

**Issue by InuYasha86000** [XCompWiz/LookingGlass#25]
I know there has been an issue with Security Craft where if you bind a camera to a frame and restart that frame after it shuts off (they turn off after 5 minutes) the cameras suddenly get faster, and keep going faster every time the frames are restarted, however,
I noticed that the Lazer lights, the strobe lights, and the records spinning in BetterRecords mod were really fast ( almost 3 to 4 times faster than normal) so I tried removing LookingGlass and it fixed the issue with BetterRecords (Security Craft without LookingGlass eliminates viewing a camera within a frame, only a handheld frame can be used).
So something with lookingglass is causing these 2 mods to speed up different parts. I can supply copies of my modpack update as this was discovered with my test version before release. I had talked to @AngrySoundTech about this issue thinking the sped up things in BetterRecords was on his end and he suggested talking to you about it.

**Comment by XCompWiz** [comment]
Are you using the absolute latest LG (0.2.0.01)?  It had some fixes to remove some double updating effects.

**Comment by InuYasha86000** [comment]
Actually LookingGlass 0.2.0.01 Crashes the client when on the server (not sure about single player as I just tried it) where as 0.2.0.00 works perfectly other than the speed up issue.
here's the crashlog for the 0.2.0.01: http://pastebin.com/zxtgNwKS

**Comment by NicholasFeldman** [comment]
Judging by that trace, it's likely an issue with the version of SecurityCraft rather than LookingGlass. The AbstractMethodError indicates that there's likely a version mismatch.

**Comment by InuYasha86000** [comment]
SecurityCraft haven't had an update for a while and I don't know when there planning to release a version.

**Comment by XCompWiz** [comment]
Weird that that broke.  The camera animation stuff didn't change.
Either way, you'll need to get SecurityCraft to fix that.

I'm going to mark this as resolved as the reported issue was for an older version of the mod and the issue has been fixed since.
