### ISSUE TITLE
Unknown Crash

### ISSUE THREAD

**Issue by Urrurrual** [XCompWiz/LookingGlass#26]
Was just starting up doing stuff on ymstcraft in my modpack was placing down blocks and i crashed with the following report.
[crash-2016-10-30_20.34.58-server.txt](https://github.com/XCompWiz/LookingGlass/files/560900/crash-2016-10-30_20.34.58-server.txt)

**Comment by Urrurrual** [comment]
Isolated issue to clicking on writing desks, moving to mystcraft-issues.

**Comment by XCompWiz** [comment]
Yup! Known issue. Sorry about that.
In the future, please pastebin the log (or similar) rather than upload it as a file. It is much easier to review issues in a browser if I don't need to download anything. :)
