### ISSUE TITLE
Crash with Securitycraft when binding a camera to monitor

### ISSUE THREAD

**Issue by ExcitedName** [XCompWiz/LookingGlass#27]
http://pastebin.com/0MUT3Vxx

**Comment by XCompWiz** [comment]
I'd appreciate a bit more text about what you were doing when you report bugs, please. :)
This looks to be an issue in Securitycraft.  I'm afraid I don't know what broke or why.

**Comment by ExcitedName** [comment]
No problem. I was attempting to link a bound camera to a frame block using Securitycraft. The manual stated that with Looking Glass installed; if I understood the instructions correctly, that it would bind that camera to the frame block rather than the monitor item. Forgive me; I'm still learning code, but what in the crash report tells you it's Securitycraft? The Head Stacktrace; and other locations, cite your mod. There must be something you see that I am unaware of. I'm not trying to challenge you; just trying to learn. I will most certainly post this with Securitycraft as well. What ever it is I hope it can be resolved. The idea of your mod working in conjunction with Securitycraft sounds pretty fun. Have a good one.

**Comment by XCompWiz** [comment]
The very first line of the trace is where it broke:

> java.lang.AbstractMethodError: net.geforcemods.securitycraft.imc.lookingglass.CameraAnimatorSecurityCamera.update(J)V

This was called by my code, so the rest of the trace is in my code, but the breakdown is in this function.
It was called by my code as the class CameraAnimatorSecurityCamera is an implementation of my own camera class, and it overrides the update function.
Hope that clarifies it! :) If there is anything else you don't understand I'm happy to explain. :)

**Comment by ExcitedName** [comment]
That makes sense. I just might take you up on that offer in the future.
Thanks a lot.
