### ISSUE TITLE
Black screen on monitor for security craft 

### ISSUE THREAD

**Issue by iGoldenPiggy** [XCompWiz/LookingGlass#29]
when i put the monitor into the frame it shows nothing but a black screen how do i fix this

**Comment by Guichaguri** [comment]
Shouldn't this be reported directly to SecurityCraft instead of LookingGlass?

**Comment by XCompWiz** [comment]
Probably, but I expect SecurityCraft isn't updating for 1.7.10 anymore.
Sorry, it's broken. Not much you can do.  Looks like it won't ever be fixed at this point (a LookingGlass update for 1.7.10 us both unlikely and would not help.)
