### ISSUE TITLE
open GL error

### ISSUE THREAD

**Issue by MoonlightSystem** [XCompWiz/LookingGlass#3]
i got a openGL error while using this mod and my screen went weird also
here is the log:
http://pastebin.com/raw.php?i=zN17vvAt

**Comment by XCompWiz** [comment]
I'm afraid that log is virtually useless.
What were you doing at the time of the error? Can you get a screenshot of what you mean by your screen going weird?

**Comment by MoonlightSystem** [comment]
never mind i fixed it

**Comment by MoonlightSystem** [comment]
i think......
