### ISSUE TITLE
Will there be an update for 1.16.5?

### ISSUE THREAD

**Issue by Alexzrequester** [XCompWiz/LookingGlass#35]
i'm currently buliding a map for FNAF and i really want to have securitycraft's cameras acessible without having to open the interface, and i really want some way to do it, but there's none unless it's looking glass.

**Comment by Alexzrequester** [comment]
by  the way, i'm sorry to just show up and ask for support for 1.16.5 out of nowhere.

**Comment by XCompWiz** [comment]
Several folks have tried updating the project to more recent versions of Minecraft, but it seems that the render changes have done it in pretty soundly. I have no plans to spend time on it, sorry.
