### ISSUE TITLE
LookingGlass 0.10.0.00 + Mystcraft 0.11.11.00 incompatible?

### ISSUE THREAD

**Issue by Xiaminou** [XCompWiz/LookingGlass#6]
I updated LookingGlass and Mystcraft today and now I can't start it because Mystcraft is asking for Looking Glass 0.0.1.01.

I tried rolling back to Mystcraft 0.11.10.00 and it stills wants LookingGlass 0.0.1.01.

Unfortunatly you removed the old version so I cannot rollback LookingGlass and I'm stuck being unable to play my modpack.

Edit: I got the old version back from the trash and it's working now.

**Comment by XCompWiz** [comment]
It's not Mystcraft asking for the older version, it's the Mystcraft NEI plugin. Remove that and you'll be able to update properly. :)

Darn it, @heldplayer! See what you caused! :P

**Comment by Xiaminou** [comment]
Oh of course, I hadn't thought of that, thanks, however can you still leave older versions of LookingGlass on Curse?

**Comment by Xiaminou** [comment]
oh and I know this is off topic but, how do you get LookingGlass to do the stuff I saw in Direwolf's forgecraft series, I installed it and tried using a book but it doesn't look like it's doing anything.

**Comment by XCompWiz** [comment]
The reason I removed the older versions is they won't do anything with newer versions of Mystcraft, much less anyone using the new API. Update and you should see the link panel effect. :)
