### ISSUE TITLE
Point of View At Top Of Nether

### ISSUE THREAD

**Issue by martindiv** [XCompWiz/LookingGlass#8]
Kind of a weird use case but if you have a link book within about 10 blocks of the top of the nether all you see is the view above the bedrock.

**Comment by XCompWiz** [comment]
That's just the view trying to adjust for not being able to see the exact target location. (It's part of the pivot animator, for anyone interested.)  Likely it couldn't figure out where the ground was where you'd link to and just shifted the view up until it found what it thought was the out location.

Not really an issue, but thanks for bringing it up! :)
